### ISSUE TITLE
RVA analytical methods landing page: more information in vocab description

### ISSUE THREAD

**Issue by mk618** [amds-ldeo/Vocabulary#2]
- add a "how to cite" citation guideline in the description or notes on https://vocabs.ardc.edu.au/viewById/650
- add cross-reference to this github repo?

**Comment by mk618** [comment]
Citation:

Richard, S. M., Klöcking, M., Luzi-Helbing, M., Johansson, A., Profeta, L., Lehnert, K. 2023. Analytical Methods for Geochemistry and Cosmochemistry. Concept Scheme for Analysis Methods in Geo- and Cosmochemistry. Version 1. Published at Research Vocabularies Australia.  https://vocabs.ardc.edu.au/viewById/650

**Comment by smrgeoinfo** [comment]
Richard, S. M., Klöcking, M., Luzi-Helbing, M., Johansson, A., Profeta, L., Lehnert, K. 2023. Analytical Methods for Geochemistry and Cosmochemistry. Concept Scheme for Analysis Methods in Geo- and Cosmochemistry. Published at Research Vocabularies Australia.  https://vocabs.ardc.edu.au/viewById/650

Add version number in citatoin
ADD Citations for each version in ardc page. Add Leander, Hannah Sweets, Bärbel Sarbas, Jenn  make version1.3 

add link to GitHub, contribute message in ARDC page.

**Comment by smrgeoinfo** [comment]
Done, updates at https://vocabs.ardc.edu.au/viewById/650
